// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data.Context;

namespace Store.Data.Migrations
{
    [DbContext(typeof(AccountContext))]
    partial class AccountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Store.Domain.Entities.Account.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Complement")
                        .HasColumnName("complement")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnName("country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Neighborhood")
                        .HasColumnName("neighborhood")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Number")
                        .HasColumnName("number")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnName("person_id")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnName("street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnName("zip_code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Brasília",
                            Country = "Brasil",
                            Neighborhood = "Taguatinga",
                            Number = 25,
                            PersonId = 1,
                            State = "DF",
                            Street = "QNB 03",
                            ZipCode = "72115030"
                        },
                        new
                        {
                            Id = 2,
                            City = "Brasilia",
                            Complement = "You Life Style, ap 309",
                            Country = "Brasil",
                            Neighborhood = "Aguas Claras",
                            Number = 18,
                            PersonId = 2,
                            State = "DF",
                            Street = "Av araucarias",
                            ZipCode = "71153-410"
                        });
                });

            modelBuilder.Entity("Store.Domain.Entities.Account.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AreaCode")
                        .HasColumnName("area_code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnName("country_code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnName("number")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("phone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaCode = "61",
                            CountryCode = "55",
                            Number = "995599415",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            AreaCode = "61",
                            CountryCode = "55",
                            Number = "996767867",
                            PersonId = 2
                        });
                });

            modelBuilder.Entity("Store.Domain.Entities.Account.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.ToTable("users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Store.Domain.Entities.Account.Person", b =>
                {
                    b.HasBaseType("Store.Domain.Entities.Account.User");

                    b.Property<DateTime>("Birthday")
                        .HasColumnName("birth_day")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("Store.Domain.Entities.Account.Client", b =>
                {
                    b.HasBaseType("Store.Domain.Entities.Account.Person");

                    b.HasDiscriminator().HasValue("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "flpinheiro@gmail.com",
                            PassWord = "12345678",
                            Birthday = new DateTime(1985, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Felipe Luís",
                            LastName = "Pinheiro"
                        });
                });

            modelBuilder.Entity("Store.Domain.Entities.Account.Employee", b =>
                {
                    b.HasBaseType("Store.Domain.Entities.Account.Person");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnName("registration")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<decimal>("Salary")
                        .HasColumnName("salary")
                        .HasColumnType("decimal(65,30)");

                    b.HasDiscriminator().HasValue("Employee");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "mrosa@gmail.com",
                            PassWord = "a mais gata",
                            Birthday = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marcelle",
                            LastName = "Rosa",
                            Registration = "1234568",
                            Salary = 3500m
                        });
                });

            modelBuilder.Entity("Store.Domain.Entities.Account.Address", b =>
                {
                    b.HasOne("Store.Domain.Entities.Account.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Store.Domain.Entities.Account.Phone", b =>
                {
                    b.HasOne("Store.Domain.Entities.Account.Person", "Person")
                        .WithMany("Phones")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
